### ISSUE TITLE
Can the idea be ported to multimodal dialogue generation task?

### ISSUE THREAD

**Issue by wdr-RA02** [ahnjaewoo/MPCHAT#4]
Hello, thank you for your amazing work! Having read the paper, I wonder if the whole idea could be of help in terms of multi-modal personalized dialogue generation task. I will post some of my preliminary ideas of mine below, and some help from you would be greatly appreciated.

Personally, I think that the output of the episodic memory encoder, h_p, would give abundant prior information of the speaker's persona.  Thus, the idea of injecting an h_p trained with the NRP(Next Response Prediction) task presented in this repo to an existing multimodal language generation model might be able to solve the problem.

I attach an image of my idea here as your reference
<img src="https://github.com/ahnjaewoo/MPCHAT/assets/6315157/ddad5ed2-bbb1-4ac5-a321-1f67db96aa0e" width=564 height=327/>

The problems I've got currently are as follows:
1) To begin, since there exists multiple ways of injecting h_p into the representation of context image, I wonder if the best way of doing this is to directly sum the h_p into the representation, rather than concatenating the vector as inputs_embeds
2) I don't know if NRP task should be done beforehand, or would it be better if I just jointly finetune the MLLM with the persona module over the MPCHAT dataset.

Thank you again for your great work, and I sincerely appreciate your thoughts on my problem.

**Comment by ahnjaewoo** [comment]
Thank you for your insightful questions and interest in our MPCHAT work!

1. The reason I chose to sum h_p at that time was that there were hardly any MLLM (i.e., multi-modal large language models) that handle multiple images, whereas, with CLIP, it's only possible to obtain embeddings for a _single_ image. Of course, concatenation is also an option instead of summation, as you have mentioned. In addition, I recommend referring to the numerous MLLM architectures that support multiple images with multimodal instruction tuning (or multimodal in-context learning), such as Open-Flamingo, Otter, the Kosmos series, Sparkles, etc.

2. As for the answer to this question, it's honestly 'I don't know since I haven't tried it.' Both methods would ultimately need to be empirically implemented and tested to see their performance. Additionally, I think that pre-training the persona module via contrastive learning between persona images and persona texts might help improve performance.

**Comment by wdr-RA02** [comment]
Thanks for the reply! In fact I've been looking into the problem recently, and will definitely take your suggestions into consideration. I will come back if I have achieved something. Thank you again for the wonderful work.
